name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Linters and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install tools
        run: |
          pip install flake8 pytest httpx

      - name: Lint Backend
        run: |
          flake8 src/backend/

      - name: Lint Frontend
        run: |
          flake8 src/frontend/

      - name: Install backend dependencies & tests
        run: |
          pip install -r src/backend/requirements.txt
          pytest src/backend/tests/

      - name: Install frontend dependencies & tests
        run: |
          pip install -r src/frontend/requirements.txt
          pytest src/frontend/tests/

  build:
    name: Build Docker Images
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3    

      - name: Build backend docker image
        run: |
          docker build -f src/backend/dockerfile -t backend:ci-latest .

      - name: Build frontend docker image
        run: |
          docker build -f src/frontend/dockerfile -t frontend:ci-latest .
