name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Linters and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install tools
        run: |
          pip install flake8 pytest httpx

      - name: Lint Backend
        run: |
          flake8 src/backend/

      - name: Lint Frontend
        run: |
          flake8 src/frontend/

      - name: Install backend dependencies & tests
        run: |
          pip install -r src/backend/requirements.txt
          PYTHONPATH=src/backend pytest src/backend/tests/

      - name: Install frontend dependencies & tests
        run: |
          pip install -r src/frontend/requirements.txt
          PYTHONPATH=src/frontend pytest src/frontend/tests/
  docker:
    name: Build & Push Docker Images
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: src/backend
          file: src/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-image:${{ github.run_id }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: src/frontend
          file: src/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:${{ github.run_id }}

